### ISSUE TITLE
Feature Request - Extension of the clip/cut function

### ISSUE THREAD

**Issue by stamogis** [bstroebl/DigitizingTools#47]
I would find it useful to extend your "cut" and "clip" functions for the topological processing of overlapping polygons. The in-place functions "clip" and "difference" offered in QGIS 3 are not so intuitive in my opinion and require many clicks to get the desired results. This is too complicated for some users.
In an interactive mode the user should only have to select the cutting polygon. After clicking on the according button, the underlying feature should be clipped/cutted. The previously required duplication of the layer is no longer necessary.
In a batch mode, several cutting polygons can be selected first. When executing the function, all affected features are then clipped/cutted.
Regards
Burghardt

**Comment by TonyShep** [comment]
I'm comfortable using either method (built in function or plugin), although I was so used to using your plugin that I would be keen to see those features reinstated.  Is it a huge problem having multiple methods to achieve the same result?  I don’t think so, there are many cases already in QGIS.  I think I would find it easier having a "toolbar" as opposed to having to have the processor toolbox open, but that is just my personal preference.

**Comment by bstroebl** [comment]
Hi @TonyShep , thanks for commenting. It is not a problem at all, but there were two reasons for removing:
1. The aim of the plugin is to provide either functions that are not available in basic QGIS (e.g. _prolong line_ which has been remove because QGIS provides its own tool now) or to provide better functions (e.g. _split features_) than what basic QGIS offers.
2. _in-place processing_ offers more functions than DigitizingTools. Why have some and not others doubled in the plugin? Moreover in-place processing is new and pointing users to this new possibility seemed to make sense for me.
@stamogis and me worked out how the tools could be resurrected providing more functionality than in-place processing. What do you think?

**Comment by bstroebl** [comment]
Tools have been rekindled in version 1.5.0, see wiki for usage

**Comment by TonyShep** [comment]
Hi Bernhard

 

I get an error when running the new 1.5.0 version.

 

Couldn't load plugin 'DigitizingTools' due to an error when calling its classFactory() method 

ImportError: cannot import name 'DtDualToolSelectPolygon' from 'dttools' (C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dttools.py) 

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Tony/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DigitizingTools\__init__.py", line 28, in classFactory
    from .digitizingtools import DigitizingTools
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Tony/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DigitizingTools\digitizingtools.py", line 38, in 
    import dtcutter
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dtcutter.py", line 23, in 
    from dttools import DtDualToolSelectPolygon
ImportError: cannot import name 'DtDualToolSelectPolygon' from 'dttools' (C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools\dttools.py)


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.2-Zanzibar Zanzibar, 4470baa1a3 

Python Path:

*                     C:/Users/Tony/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\trail_elevation_stats

*                     C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python

*                     C:/Users/Tony/AppData/Roaming/QGIS/QGIS3\profiles\default/python

*                     C:/Users/Tony/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins

*                     C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins

*                     C:\Program Files\QGIS 3.8\bin\python37.zip

*                     C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs

*                     C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib

*                     C:\Program Files\QGIS 3.8\bin

*                     C:\PROGRA~1\QGIS3~1.8\apps\Python37

*                     C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages

*                     C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32

*                     C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib

*                     C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin

*                     C:/Users/Tony/AppData/Roaming/QGIS/QGIS3\profiles\default/python

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\linz-data-importer

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

*                     N:/AssetFinda Data

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools

*                     C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools

C:\Users\Tony\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools

**Comment by bstroebl** [comment]
be sure to close QGIS, if that doesn't help deinstall the plugin and install again
